name: multiq
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - ca-certificates=2022.10.11=h06a4308_0
  - certifi=2021.5.30=py36h5fab9bb_0
  - click=8.0.1=py36h5fab9bb_0
  - coloredlogs=15.0.1=py36h5fab9bb_1
  - colormath=3.0.0=py_2
  - commonmark=0.9.1=py_0
  - cycler=0.11.0=pyhd8ed1ab_0
  - dataclasses=0.8=pyh787bdff_2
  - fastqc=0.11.9=hdfd78af_1
  - font-ttf-dejavu-sans-mono=2.37=hd3eb1b0_0
  - fontconfig=2.13.1=hef1e5e3_1
  - freetype=2.12.1=hca18f0e_0
  - future=0.18.2=py36h5fab9bb_3
  - gdbm=1.18=hd4cb3f1_4
  - humanfriendly=10.0=py36h5fab9bb_0
  - icu=58.2=he6710b0_3
  - importlib-metadata=4.8.1=py36h5fab9bb_0
  - jinja2=3.0.3=pyhd8ed1ab_0
  - jpeg=9e=h166bdaf_2
  - kiwisolver=1.3.1=py36h605e78d_1
  - lcms2=2.12=hddcbb42_0
  - ld_impl_linux-64=2.36.1=hea4e1c9_2
  - libblas=3.9.0=16_linux64_openblas
  - libcblas=3.9.0=16_linux64_openblas
  - libffi=3.4.2=h7f98852_5
  - libgcc-ng=12.1.0=h8d9b700_16
  - libgfortran-ng=12.1.0=h69a702a_16
  - libgfortran5=12.1.0=hdcd56e2_16
  - libgomp=12.1.0=h8d9b700_16
  - liblapack=3.9.0=16_linux64_openblas
  - libnsl=2.0.0=h7f98852_0
  - libopenblas=0.3.21=pthreads_h78a6416_2
  - libpng=1.6.37=h753d276_4
  - libsqlite=3.39.2=h753d276_1
  - libstdcxx-ng=12.1.0=ha89aaad_16
  - libtiff=4.2.0=hf544144_3
  - libuuid=1.41.5=h5eee18b_0
  - libwebp-base=1.2.4=h166bdaf_0
  - libxml2=2.9.14=h74e7548_0
  - libzlib=1.2.12=h166bdaf_2
  - lzstring=1.0.4=py_1001
  - markdown=3.4.1=pyhd8ed1ab_0
  - markupsafe=2.0.1=py36h8f6f2f9_0
  - matplotlib-base=3.3.4=py36hd391965_0
  - multiqc=1.13=pyhdfd78af_0
  - ncurses=6.3=h27087fc_1
  - networkx=2.7.1=pyhd8ed1ab_0
  - numpy=1.19.5=py36hfc0c790_2
  - olefile=0.46=pyh9f0ad1d_1
  - openjdk=8.0.152=h7b6447c_3
   - openjpeg=2.4.0=hb52868f_1
  - openssl=1.1.1s=h7f8727e_0
  - pandas=1.1.5=py36h284efc9_0
  - perl=5.34.0=h5eee18b_2
  - pillow=8.2.0=py36ha6010c0_1
  - pip=21.3.1=pyhd8ed1ab_0
  - pygments=2.13.0=pyhd8ed1ab_0
  - pyparsing=3.0.9=pyhd8ed1ab_0
  - python=3.6.15=hb7a2778_0_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python_abi=3.6=2_cp36m
  - pytz=2022.2.1=pyhd8ed1ab_0
  - pyyaml=5.4.1=py36h8f6f2f9_1
  - readline=8.1.2=h0f457ee_0
  - requests=2.13.0=py36_0
  - rich=12.5.1=pyhd8ed1ab_0
  - rich-click=1.3.0=pyhd8ed1ab_0
  - scipy=1.5.3=py36h81d768a_1
  - setuptools=58.0.4=py36h5fab9bb_2
  - simplejson=3.8.1=py36_0
  - six=1.16.0=pyh6c4a22f_0
  - spectra=0.0.11=py_1
  - sqlite=3.39.2=h4ff8645_1
  - tk=8.6.12=h27826a3_0
  - tornado=6.1=py36h8f6f2f9_1
  - typing_extensions=4.1.1=pyha770c72_0
  - wheel=0.37.1=pyhd8ed1ab_0
  - xz=5.2.6=h166bdaf_0
  - yaml=0.2.5=h7f98852_2
  - zipp=3.6.0=pyhd8ed1ab_0
  - zlib=1.2.12=h166bdaf_2
  - zstd=1.5.2=h6239696_4
