name: short-read-quality-control
channels:
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - _sysroot_linux-64_curr_repodata_hack=3=h5bd9786_13
  - adapterremoval=2.3.3=pl5321h19e8d03_0
  - aioeasywebdav=2.4.0=py38h578d9bd_1001
  - aiohttp=3.8.1=py38h0a891b7_1
  - aiosignal=1.2.0=pyhd8ed1ab_0
  - amply=0.1.5=pyhd8ed1ab_0
  - appdirs=1.4.4=pyh9f0ad1d_0
  - async-timeout=4.0.2=pyhd8ed1ab_0
  - attmap=0.13.2=pyhd8ed1ab_0
  - attrs=22.1.0=pyh71513ae_1
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
  - bcrypt=3.2.2=py38h0a891b7_0
  - boto3=1.24.60=pyhd8ed1ab_0
  - botocore=1.27.60=pyhd8ed1ab_0
  - bowtie2=2.4.5=py38hfbc8389_3
  - brotlipy=0.7.0=py38h0a891b7_1004
  - bump2version=1.0.1=pyh9f0ad1d_0
  - bzip2=1.0.8=h7f98852_4
  - c-ares=1.18.1=h7f98852_0
  - ca-certificates=2022.12.7=ha878542_0
  - cachetools=5.2.0=pyhd8ed1ab_0
  - certifi=2022.12.7=pyhd8ed1ab_0
  - cffi=1.15.1=py38h4a40e3a_0
  - charset-normalizer=2.1.1=pyhd8ed1ab_0
  - click=8.1.3=py38h578d9bd_0
  - click-default-group=1.2.4=pyhd8ed1ab_0
  - coin-or-cbc=2.10.8=h3786ebc_0
  - coin-or-cgl=0.60.6=h6f57e76_1
  - coin-or-clp=1.17.7=hc56784d_1
  - coin-or-osi=0.108.7=h2720bb7_1
  - coin-or-utils=2.11.6=h202d8b1_1
  - coincbc=2.10.8=0_metapackage
  - commonmark=0.9.1=py_0
  - configargparse=1.5.3=pyhd8ed1ab_0
  - connection_pool=0.0.3=pyhd3deb0d_0
  - cryptography=37.0.4=py38h2b5fc30_0
  - dataclasses=0.8=pyhc8e2a94_3
  - datrie=0.8.2=py38h497a2fe_3
  - decorator=5.1.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - docutils=0.19=py38h578d9bd_0
  - dpath=2.0.6=py38h578d9bd_1
  - dropbox=11.33.0=pyhd8ed1ab_0
  - fastp=0.22.0=h2e03b76_0
  - filechunkio=1.8=py_2
  - filelock=3.8.0=pyhd8ed1ab_0
  - frozenlist=1.3.1=py38h0a891b7_0
  - ftputil=5.0.4=pyhd8ed1ab_0
  - future=0.18.2=py38h578d9bd_5
  - gitdb=4.0.9=pyhd8ed1ab_0
  - gitpython=3.1.27=pyhd8ed1ab_0
  - google-api-core=2.8.2=pyhd8ed1ab_0
  - google-api-python-client=2.58.0=pyhd8ed1ab_0
  - google-auth=2.11.0=pyh6c4a22f_0
  - google-auth-httplib2=0.1.0=pyhd8ed1ab_1
  - google-cloud-core=2.3.2=pyhd8ed1ab_0
  - google-cloud-storage=2.5.0=pyh6c4a22f_0
  - google-crc32c=1.1.2=py38h57c428a_3
  - google-resumable-media=2.3.3=pyhd8ed1ab_0
  - googleapis-common-protos=1.56.4=py38h578d9bd_0
  - grpc-cpp=1.48.0=hbad87ad_3
  - grpcio=1.48.0=py38h5b6373e_3
  - httplib2=0.20.4=pyhd8ed1ab_0
  - idna=3.3=pyhd8ed1ab_0
  - importlib-metadata=4.11.4=py38h578d9bd_0
  - importlib_resources=5.9.0=pyhd8ed1ab_0
  - iniconfig=1.1.1=pyh9f0ad1d_0
  - jinja2=3.1.2=pyhd8ed1ab_1
  - jmespath=1.0.1=pyhd8ed1ab_0
  - jsonschema=4.14.0=pyhd8ed1ab_0
  - jupyter_core=4.11.1=py38h578d9bd_0
  - kernel-headers_linux-64=2.6.32=he073ed8_15
  - ld_impl_linux-64=2.36.1=hea4e1c9_2
  - libabseil=20220623.0=cxx17_h48a1fff_1
  - libblas=3.9.0=16_linux64_openblas
  - libcblas=3.9.0=16_linux64_openblas
  - libcrc32c=1.1.2=h9c3ff4c_0
  - libffi=3.4.2=h7f98852_5
  - libgcc-ng=12.1.0=h8d9b700_16
  - libgfortran-ng=12.1.0=h69a702a_16
  - libgfortran5=12.1.0=hdcd56e2_16
  - libgomp=12.1.0=h8d9b700_16
  - liblapack=3.9.0=16_linux64_openblas
  - liblapacke=3.9.0=16_linux64_openblas
  - libnsl=2.0.0=h7f98852_0
  - libopenblas=0.3.21=pthreads_h78a6416_2
  - libprotobuf=3.20.1=h6239696_1
  - libsodium=1.0.18=h36c2ea0_1
  - libsqlite=3.39.2=h753d276_1
  - libstdcxx-ng=12.1.0=ha89aaad_16
  - libuuid=2.32.1=h7f98852_1000
  - libzlib=1.2.12=h166bdaf_2
  - llvm-openmp=8.0.1=hc9558a2_0
  - logmuse=0.2.6=pyh8c360ce_0
  - markupsafe=2.1.1=py38h0a891b7_1
  - multidict=6.0.2=py38h0a891b7_1
  - nbformat=5.4.0=pyhd8ed1ab_0
  - ncurses=6.3=h27087fc_1
  - numpy=1.23.2=py38h3a7f9d9_0
  - oauth2client=4.1.3=py_0
  - openmp=8.0.1=0
  - openssl=1.1.1s=h0b41bf4_1
  - packaging=21.3=pyhd8ed1ab_0
  - pandas=1.4.3=py38h47df419_0
  - paramiko=2.11.0=pyhd8ed1ab_0
  - peppy=0.34.0=pyhd8ed1ab_0
  - perl=5.32.1=2_h7f98852_perl5
  - pip=22.2.2=pyhd8ed1ab_0
  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_0
  - plac=1.3.5=pyhd8ed1ab_0
  - pluggy=1.0.0=py38h578d9bd_3
  - ply=3.11=py_1
  - prettytable=3.4.0=pyhd8ed1ab_0
  - protobuf=3.20.1=py38hfa26641_0
  - psutil=5.9.1=py38h0a891b7_0
  - pulp=2.6.0=py38h578d9bd_1
  - py=1.11.0=pyh6c4a22f_0
  - pyasn1=0.4.8=py_0
  - pyasn1-modules=0.2.7=py_0
  - pycparser=2.21=pyhd8ed1ab_0
  - pygments=2.13.0=pyhd8ed1ab_0
  - pynacl=1.5.0=py38h0a891b7_1
  - pyopenssl=22.0.0=pyhd8ed1ab_0
  - pyparsing=3.0.9=pyhd8ed1ab_0
  - pyrsistent=0.18.1=py38h0a891b7_1
  - pysftp=0.2.9=py_1
  - pysocks=1.7.1=py38h578d9bd_5
  - pytest=7.1.2=py38h578d9bd_0
  - python=3.8.13=h582c2e5_0_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python-fastjsonschema=2.16.1=pyhd8ed1ab_0
  - python-irodsclient=1.1.4=pyhd8ed1ab_0
  - python_abi=3.8=2_cp38
  - pytz=2022.2.1=pyhd8ed1ab_0
  - pyu2f=0.1.5=pyhd8ed1ab_0
  - pyyaml=6.0=py38h0a891b7_4
  - ratelimiter=1.2.0=py_1002
  - re2=2022.06.01=h27087fc_0
  - readline=8.1.2=h0f457ee_0
  - requests=2.28.1=pyhd8ed1ab_0
  - retry=0.9.2=py_0
  - rich=12.5.1=pyhd8ed1ab_0
  - rsa=4.9=pyhd8ed1ab_0
  - s3transfer=0.6.0=pyhd8ed1ab_0
  - samtools=1.3.1=0
  - setuptools=65.3.0=py38h578d9bd_0
  - six=1.16.0=pyh6c4a22f_0
  - slacker=0.14.0=py_0
  - smart_open=6.1.0=pyha770c72_1
  - smmap=3.0.5=pyh44b312d_0
  - snakemake=7.12.1=hdfd78af_0
  - snakemake-minimal=7.12.1=pyhdfd78af_0
  - spades=3.14.1=h95f258a_2
  - sqlite=3.39.2=h4ff8645_1
  - stone=3.3.1=pyhd8ed1ab_0
  - stopit=1.1.2=py_0
  - sysroot_linux-64=2.12=he073ed8_15
  - tabulate=0.8.10=pyhd8ed1ab_0
  - tbb=2020.2=h4bd325d_4
  - tk=8.6.12=h27826a3_0
  - tomli=2.0.1=pyhd8ed1ab_0
  - toposort=1.7=pyhd8ed1ab_0
  - traitlets=5.3.0=pyhd8ed1ab_0
  - typing-extensions=4.3.0=hd8ed1ab_0
  - typing_extensions=4.3.0=pyha770c72_0
  - ubiquerg=0.6.2=pyhd8ed1ab_0
  - uritemplate=4.1.1=pyhd8ed1ab_0
  - urllib3=1.26.11=pyhd8ed1ab_0
  - veracitools=0.1.3=py_0
  - wcwidth=0.2.5=pyh9f0ad1d_2
  - wheel=0.37.1=pyhd8ed1ab_0
  - wrapt=1.14.1=py38h0a891b7_0
  - xz=5.2.6=h166bdaf_0
  - yaml=0.2.5=h7f98852_2
  - yarl=1.7.2=py38h0a891b7_2
  - yte=1.5.1=py38h578d9bd_0
  - zipp=3.8.1=pyhd8ed1ab_0
  - zlib=1.2.12=h166bdaf_2
  - zstd=1.5.2=h6239696_4
  - pip:
    - appdirs==1.4.4
    - certifi==2022.9.24
    - charset-normalizer==2.1.1
    - click-default-group==1.2.2
    - configargparse==1.5.3
    - connection-pool==0.0.3
    - datrie==0.8.2
    - docutils==0.19
    - dpath==2.0.6
    - fastjsonschema==2.16.2
    - gitdb==4.0.9
    - gitpython==3.1.29
    - idna==3.4
    - importlib-resources==5.10.0
    - jinja2==3.1.2
    - jsonschema==4.17.0
    - jupyter-core==5.0.0
    - markupsafe==2.1.1
    - nbformat==5.7.0
    - numpy==1.23.4
    - pandas==1.5.1
    - pkgutil-resolve-name==1.3.10
    - plac==1.3.5
    - platformdirs==2.5.4
    - psutil==5.9.4
    - pulp==2.7.0
    - pyrsistent==0.19.2
    - python-dateutil==2.8.2
    - pytz==2022.6
    - pyyaml==6.0
    - requests==2.28.1
    - reretry==0.11.1
    - six==1.16.0
    - smart-open==6.2.0
    - smmap==5.0.0
    - snakemake==7.18.2
    - stopit==1.1.2
    - tabulate==0.9.0
    - throttler==1.2.1
    - toposort==1.7
    - traitlets==5.5.0
    - urllib3==1.26.12
    - wrapt==1.14.1
    - yte==1.5.1
    - zipp==3.10.0
