#'''Parameters'''#


# --- general --- #

minqual:    30


# --- filter_low_qual --- #

dedup:      False


# --- filter_adapters --- #

# '/path/to/camp_short-read-quality-control/workflow/ext/common_adapters.txt'
adapters: ''


# --- filter_host_reads --- #

use_host_filter:         False
host_reference_database: ''


# --- filter_seq_errors --- #

# Options (must choose one): 'bayeshammer', 'tadpole'
error_correction: 'tadpole'


# --- qc-option --- #

qc_dataviz: True